In [54]:
import numpy as np

In [55]:
a = np.sin(45)
b = np.cos(90)
c = np.tan(60*np.pi/180)
d = np.sin(np.pi/6)
a, b, c, d

(0.8509035245341184,
 -0.4480736161291701,
 1.7320508075688767,
 0.49999999999999994)

In [56]:
x = np.deg2rad(60)
x

1.0471975511965976

In [57]:
e = np.round(34.78950)
e1 = np.round(45.86824,1)
e2 = np.round(56.32889,2)
e3 = np.round(45.23628,3)
e, e1, e2, e3

(35.0, 45.9, 56.33, 45.236)

In [58]:
f1 = np.ceil(56.240)
f2 = np.floor(45.996)
f1, f2

(57.0, 45.0)

In [59]:
g1 = np.mod(40, 6)
g2 = np.power(4, 5)
print(g1, g2)

4 1024


In [60]:
h = [3, 5, 7, 8, 9, 11]
ar = np.array(h)
print(ar)

[ 3  5  7  8  9 11]


In [61]:
j = [[2, 3, 4], [5, 6, 7], [8, 9, 10]]
ar2 = np.array(j)
print(ar2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [62]:
k = np.array([('hasan', 34, 67.9), ('ahmad', 28, 72.5), ('reem', 31, 80.6)], 
            dtype = [('name', 'U5'), ('old', 'i2'), ('mark', 'f4')])
print(k)

[('hasan', 34, 67.9) ('ahmad', 28, 72.5) ('reem', 31, 80.6)]


In [63]:
l = np.empty((4,5))
print(l)

[[1.92418420e-312 6.27463370e-322 0.00000000e+000 0.00000000e+000
  6.23059386e-307]
 [5.30276956e+180 3.31033942e-033 6.97935766e-076 3.86226062e-086
  3.35710079e-143]
 [6.01433264e+175 6.93885958e+218 5.56218858e+180 3.94356143e+180
  3.05811420e-057]
 [7.18835943e-067 1.25585535e-075 1.25740299e-071 5.43785078e-143
  1.50008929e+248]]


In [64]:
m = np.zeros((6,6))
print(m)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [65]:
n = np.ones((6,7))
print(n)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [66]:
n2 = np.eye(5)
print(n2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [67]:
nr = np.random.random((4,3))
print(nr)

[[0.16066393 0.94704814 0.7229006 ]
 [0.50176349 0.30433652 0.19275976]
 [0.33688777 0.4392833  0.04067636]
 [0.18479229 0.09654169 0.52680155]]


In [68]:
nr1 = np.random.normal(0,3,12)
print(nr1)

[-1.27820608  3.67023798  3.35471656 -1.4298245  -0.54545611 -1.01291902
  0.29614084 -1.50243856  1.03485873 -0.50358154 -3.16238075 -0.27533365]


In [69]:
nr2 = np.random.randint(200)
nr3 = np.random.randint(12, size=5)
nr4 = np.random.randint(2, 25, size=10)
nr5 = np.random.randint(1, 15, (3, 4))
print(nr2, nr3, nr4, nr5)

53 [4 2 2 2 9] [14 10 11 11 24 11 13 11 17 23] [[ 8  7  2  9]
 [ 4  2  9 12]
 [ 2  9  3  7]]


In [70]:
nr6 = np.random.rand(22)
nr7 = np.random.rand(4, 6)
nr8 = np.random.rand(2, 4, 4)
print(nr6, nr7, nr8)

[0.6583387  0.76515125 0.97177573 0.26778125 0.85983437 0.50960036
 0.47810566 0.26108297 0.91165252 0.15077257 0.85155034 0.34450678
 0.98877482 0.61630887 0.01245808 0.45134139 0.37830842 0.53768134
 0.88230905 0.61234745 0.918323   0.05777356] [[0.69718643 0.03472222 0.69167172 0.08637003 0.14287015 0.15140212]
 [0.29513649 0.31797549 0.03898499 0.00930366 0.98134275 0.76455413]
 [0.07533212 0.09263591 0.25440135 0.7842309  0.37033786 0.7126712 ]
 [0.49626563 0.18114193 0.55933591 0.4356046  0.85304096 0.28624636]] [[[0.38703207 0.60784847 0.02650986 0.22609445]
  [0.21159944 0.26071312 0.07013374 0.82634666]
  [0.60935751 0.81442719 0.14369895 0.24477815]
  [0.99399982 0.36205827 0.32063809 0.27606764]]

 [[0.76192418 0.66873507 0.72499743 0.29247984]
  [0.94472449 0.47952292 0.89525613 0.07144572]
  [0.07818381 0.81666105 0.82787864 0.04528791]
  [0.47397587 0.58854824 0.20182872 0.49543921]]]


In [71]:
p = [5, 7, 8, 9, 11, 4, 109, 26, 45, 11, 8, 4, 99]
np.random.choice(p)

11

In [72]:
np.random.shuffle(p)
print(p)

[99, 5, 4, 8, 9, 7, 4, 11, 11, 8, 109, 26, 45]


In [73]:
q = np.full((5, 6), 40)
print(q)

[[40 40 40 40 40 40]
 [40 40 40 40 40 40]
 [40 40 40 40 40 40]
 [40 40 40 40 40 40]
 [40 40 40 40 40 40]]


In [74]:
r = np.arange(20).reshape(4,5)
print(r)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [75]:
r2 = np.arange(35)
r3 = r2.reshape(5, 7)
print(r3)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [76]:
np.random.shuffle(r2)
r5 = r2.reshape(5, 7)
print(r5)

[[20  2 25  5 21  0 32]
 [16 13 29 18  3 12 24]
 [23 26 11  9 31  8  1]
 [27  7 15 28 30 33 19]
 [22 17 10  6 34  4 14]]


In [77]:
s = np.linspace(5, 10)
s2 = np.linspace(5, 20, 10)
print(s, s2)

[ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.65306122  7.75510204  7.85714286  7.95918367
  8.06122449  8.16326531  8.26530612  8.36734694  8.46938776  8.57142857
  8.67346939  8.7755102   8.87755102  8.97959184  9.08163265  9.18367347
  9.28571429  9.3877551   9.48979592  9.59183673  9.69387755  9.79591837
  9.89795918 10.        ] [ 5.          6.66666667  8.33333333 10.         11.66666667 13.33333333
 15.         16.66666667 18.33333333 20.        ]


In [78]:
s3 = np.linspace(2, 35, 12).reshape(3, 4)
print(s3)

[[ 2.  5.  8. 11.]
 [14. 17. 20. 23.]
 [26. 29. 32. 35.]]


In [79]:
t = np.diag(np.array([2, 4, 6, 7, 8]))
t2 = np.diag(np.array([3, 6, 7, 1, 4, 9]), k=4)
print(t)

[[2 0 0 0 0]
 [0 4 0 0 0]
 [0 0 6 0 0]
 [0 0 0 7 0]
 [0 0 0 0 8]]


In [80]:
print(t2)

[[0 0 0 0 3 0 0 0 0 0]
 [0 0 0 0 0 6 0 0 0 0]
 [0 0 0 0 0 0 7 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 0 9]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [81]:
np.count_nonzero(t)

5

In [82]:
np.count_nonzero(t>2)

4

In [83]:
np.count_nonzero(t>3, axis=1)

array([0, 1, 1, 1, 1], dtype=int64)

In [84]:
np.count_nonzero(t>5, axis=0)

array([0, 0, 1, 1, 1], dtype=int64)

In [85]:
np.any(t>5)

True

In [86]:
np.all(t<7, axis=1)

array([ True,  True,  True, False, False])

In [87]:
tt = t>3
print(tt)

[[False False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


In [88]:
print(t[tt])

[4 6 7 8]


In [89]:
print(t[t<0])

[]


In [90]:
cl1 = np.random.randint(1, 20, (4,4))
cl2 = np.random.randint(1, 20, (4,4))
print(cl1)

[[16  3  5  9]
 [ 8 14 12 17]
 [18  3 14  8]
 [ 5  3 15  5]]


In [91]:
print(cl2)

[[ 4  2  7 10]
 [16  1  4 14]
 [ 3  4  2 13]
 [ 6  9  9 14]]


In [92]:
np.isclose(cl1, cl2, rtol=0)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [93]:
np.multiply(cl1, 2, out=cl2)

array([[32,  6, 10, 18],
       [16, 28, 24, 34],
       [36,  6, 28, 16],
       [10,  6, 30, 10]])

In [94]:
np.power(cl2, 3, out=cl1)

array([[32768,   216,  1000,  5832],
       [ 4096, 21952, 13824, 39304],
       [46656,   216, 21952,  4096],
       [ 1000,   216, 27000,  1000]])

In [95]:
np.add.reduce(cl1, axis=1) #axis=1 --> Rows, axis=0 --> Columns

array([39816, 79176, 72920, 29216])

In [96]:
np.multiply.reduce(cl2, axis=0)

array([184320,   6048, 201600,  97920])

In [97]:
cl3 = np.multiply.outer(cl1, cl2)
print(cl3)

[[[[1048576  196608  327680  589824]
   [ 524288  917504  786432 1114112]
   [1179648  196608  917504  524288]
   [ 327680  196608  983040  327680]]

  [[   6912    1296    2160    3888]
   [   3456    6048    5184    7344]
   [   7776    1296    6048    3456]
   [   2160    1296    6480    2160]]

  [[  32000    6000   10000   18000]
   [  16000   28000   24000   34000]
   [  36000    6000   28000   16000]
   [  10000    6000   30000   10000]]

  [[ 186624   34992   58320  104976]
   [  93312  163296  139968  198288]
   [ 209952   34992  163296   93312]
   [  58320   34992  174960   58320]]]


 [[[ 131072   24576   40960   73728]
   [  65536  114688   98304  139264]
   [ 147456   24576  114688   65536]
   [  40960   24576  122880   40960]]

  [[ 702464  131712  219520  395136]
   [ 351232  614656  526848  746368]
   [ 790272  131712  614656  351232]
   [ 219520  131712  658560  219520]]

  [[ 442368   82944  138240  248832]
   [ 221184  387072  331776  470016]
   [ 497664   82944  387

In [98]:
np.add.accumulate(cl3)

array([[[[1048576,  196608,  327680,  589824],
         [ 524288,  917504,  786432, 1114112],
         [1179648,  196608,  917504,  524288],
         [ 327680,  196608,  983040,  327680]],

        [[   6912,    1296,    2160,    3888],
         [   3456,    6048,    5184,    7344],
         [   7776,    1296,    6048,    3456],
         [   2160,    1296,    6480,    2160]],

        [[  32000,    6000,   10000,   18000],
         [  16000,   28000,   24000,   34000],
         [  36000,    6000,   28000,   16000],
         [  10000,    6000,   30000,   10000]],

        [[ 186624,   34992,   58320,  104976],
         [  93312,  163296,  139968,  198288],
         [ 209952,   34992,  163296,   93312],
         [  58320,   34992,  174960,   58320]]],


       [[[1179648,  221184,  368640,  663552],
         [ 589824, 1032192,  884736, 1253376],
         [1327104,  221184, 1032192,  589824],
         [ 368640,  221184, 1105920,  368640]],

        [[ 709376,  133008,  221680,  399024],
 

In [99]:
np.multiply.accumulate(cl3)

array([[[[    1048576,      196608,      327680,      589824],
         [     524288,      917504,      786432,     1114112],
         [    1179648,      196608,      917504,      524288],
         [     327680,      196608,      983040,      327680]],

        [[       6912,        1296,        2160,        3888],
         [       3456,        6048,        5184,        7344],
         [       7776,        1296,        6048,        3456],
         [       2160,        1296,        6480,        2160]],

        [[      32000,        6000,       10000,       18000],
         [      16000,       28000,       24000,       34000],
         [      36000,        6000,       28000,       16000],
         [      10000,        6000,       30000,       10000]],

        [[     186624,       34992,       58320,      104976],
         [      93312,      163296,      139968,      198288],
         [     209952,       34992,      163296,       93312],
         [      58320,       34992,      174960, 

In [100]:
cl3.size

256

In [101]:
cl3.shape

(4, 4, 4, 4)

In [102]:
cl3.ndim

4

In [103]:
cl3.dtype

dtype('int32')

In [104]:
rx = np.matrix('{} {} ; {} {}'.format(2, 3, 4, 5))
print(rx)

[[2 3]
 [4 5]]


In [105]:
np.trace(rx) # جمع قيم القطر الرئيسي

7

In [106]:
np.linalg.det(rx) #value

-2.0

In [107]:
np.linalg.det(cl1) #value

8.473630541934195e+16

In [108]:
np.linalg.eig(rx) #eigan value

(array([-0.27491722,  7.27491722]), matrix([[-0.79681209, -0.49436913],
         [ 0.60422718, -0.86925207]]))

In [109]:
#index in arrays = index in lists
rx[1]

matrix([[4, 5]])

In [110]:
cl2[2:4]

array([[36,  6, 28, 16],
       [10,  6, 30, 10]])

In [111]:
cl3[1:12:2]

array([[[[ 131072,   24576,   40960,   73728],
         [  65536,  114688,   98304,  139264],
         [ 147456,   24576,  114688,   65536],
         [  40960,   24576,  122880,   40960]],

        [[ 702464,  131712,  219520,  395136],
         [ 351232,  614656,  526848,  746368],
         [ 790272,  131712,  614656,  351232],
         [ 219520,  131712,  658560,  219520]],

        [[ 442368,   82944,  138240,  248832],
         [ 221184,  387072,  331776,  470016],
         [ 497664,   82944,  387072,  221184],
         [ 138240,   82944,  414720,  138240]],

        [[1257728,  235824,  393040,  707472],
         [ 628864, 1100512,  943296, 1336336],
         [1414944,  235824, 1100512,  628864],
         [ 393040,  235824, 1179120,  393040]]],


       [[[  32000,    6000,   10000,   18000],
         [  16000,   28000,   24000,   34000],
         [  36000,    6000,   28000,   16000],
         [  10000,    6000,   30000,   10000]],

        [[   6912,    1296,    2160,    3888],
 

In [112]:
cl2[-3] 

array([16, 28, 24, 34])

In [113]:
cl1[0, 3]

5832

In [114]:
cl2[:, 2] #2D

array([10, 24, 28, 30])

In [115]:
cl2[3,:] #2D

array([10,  6, 30, 10])

In [116]:
cl3[1,2]   #4D

array([[442368,  82944, 138240, 248832],
       [221184, 387072, 331776, 470016],
       [497664,  82944, 387072, 221184],
       [138240,  82944, 414720, 138240]])

In [117]:
cl3[2, 1, 3]  #4D

array([2160, 1296, 6480, 2160])

In [118]:
cl3[1, 2, 1, 3]  #4D

470016

In [123]:
c22 = np.random.random(36).reshape(6, 6)
print(c22)

[[0.77222493 0.44469879 0.91573194 0.50658227 0.21844743 0.04583747]
 [0.29393172 0.47174968 0.58932516 0.97138906 0.9608056  0.33976579]
 [0.85985979 0.03242621 0.27931008 0.13730714 0.81945829 0.33237913]
 [0.24441528 0.1324983  0.03878594 0.08865278 0.30403916 0.55259879]
 [0.02850578 0.77856831 0.1056334  0.25278421 0.7914477  0.12690947]
 [0.29149183 0.52238028 0.25015117 0.18414684 0.45859673 0.62656534]]


In [124]:
c22[1:4:2] #index with 2step

array([[0.29393172, 0.47174968, 0.58932516, 0.97138906, 0.9608056 ,
        0.33976579],
       [0.24441528, 0.1324983 , 0.03878594, 0.08865278, 0.30403916,
        0.55259879]])

In [125]:
c22[::2, :5:2]

array([[0.77222493, 0.91573194, 0.21844743],
       [0.85985979, 0.27931008, 0.81945829],
       [0.02850578, 0.1056334 , 0.7914477 ]])

In [126]:
c22[:, :] = 1
print(c22)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [127]:
c22[2:4, 1:5:2] = 2.55
print(c22)

[[1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.  ]
 [1.   2.55 1.   2.55 1.   1.  ]
 [1.   2.55 1.   2.55 1.   1.  ]
 [1.   1.   1.   1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.  ]]


In [129]:
c23 = c22[::2, 1:5:2].copy()
print(c23)

[[1.   1.  ]
 [2.55 2.55]
 [1.   1.  ]]


In [137]:
s = [543, 353, 968, 64, 844, 804, 267, 355, 265, 989, 362, 654, 190]
s1, s2, s3 = np.split(s, (4,8))
print('s1 : ', s1, ' \ns2 : ', s2, ' \ns3 : ', s3)

s1 :  [543 353 968  64]  
s2 :  [844 804 267 355]  
s3 :  [265 989 362 654 190]


In [140]:
c23[1][0]

2.55

In [142]:
s4 = np.vstack((s1, s2)) #vertical stack
print(s4)

[[543 353 968  64]
 [844 804 267 355]]


In [146]:
s5 = np.hstack((s2,s3)) #horizontal stack
print(s5)

[844 804 267 355 265 989 362 654 190]


In [152]:
co1 = np.random.randint(5, 30, size=25).reshape(5, 5)
co2 = np.random.randint(10, 60, size=25).reshape(5, 5)
co12 = np.concatenate([co1, co2], axis=1)
print(co12)

[[25 29 18  9 13 26 13 49 36 27]
 [27  9 21 23 25 51 42 40 13 56]
 [18 22  6 11 17 15 19 45 40 52]
 [28  8 19 28 22 13 14 25 26 55]
 [10 25  5 11 24 27 58 46 28 48]]


In [153]:
co21 = np.concatenate([co1, co2], axis=0)
print(co21)

[[25 29 18  9 13]
 [27  9 21 23 25]
 [18 22  6 11 17]
 [28  8 19 28 22]
 [10 25  5 11 24]
 [26 13 49 36 27]
 [51 42 40 13 56]
 [15 19 45 40 52]
 [13 14 25 26 55]
 [27 58 46 28 48]]


In [156]:
mx = np.max(co12)
mn = np.min(co21)
armx = np.argmax(co12)
armn = np.argmin(co21)
print('max : ', mx, '\nmin : ', mn, '\nargmax : ', armx, '\nargmin : ', armn)

max :  58 
min :  5 
argmax :  46 
argmin :  22


In [159]:
print('variance : ', np.var(co12), '\ncovariance : \n', np.cov(co12))

variance :  207.5444 
covariance : 
 [[145.38888889  15.16666667 133.27777778  16.33333333  64.55555556]
 [ 15.16666667 250.01111111  84.61111111  87.04444444 166.73333333]
 [133.27777778  84.61111111 240.72222222 125.66666667 174.77777778]
 [ 16.33333333  87.04444444 125.66666667 167.06666667  42.26666667]
 [ 64.55555556 166.73333333 174.77777778  42.26666667 310.17777778]]


In [161]:
co1 + co2

array([[51, 42, 67, 45, 40],
       [78, 51, 61, 36, 81],
       [33, 41, 51, 51, 69],
       [41, 22, 44, 54, 77],
       [37, 83, 51, 39, 72]])

In [162]:
co1 - co2

array([[ -1,  16, -31, -27, -14],
       [-24, -33, -19,  10, -31],
       [  3,   3, -39, -29, -35],
       [ 15,  -6,  -6,   2, -33],
       [-17, -33, -41, -17, -24]])

In [163]:
co1 * co2

array([[ 650,  377,  882,  324,  351],
       [1377,  378,  840,  299, 1400],
       [ 270,  418,  270,  440,  884],
       [ 364,  112,  475,  728, 1210],
       [ 270, 1450,  230,  308, 1152]])

In [164]:
co1 / co2

array([[0.96153846, 2.23076923, 0.36734694, 0.25      , 0.48148148],
       [0.52941176, 0.21428571, 0.525     , 1.76923077, 0.44642857],
       [1.2       , 1.15789474, 0.13333333, 0.275     , 0.32692308],
       [2.15384615, 0.57142857, 0.76      , 1.07692308, 0.4       ],
       [0.37037037, 0.43103448, 0.10869565, 0.39285714, 0.5       ]])

In [166]:
np.sin(co1)

array([[-0.13235175, -0.66363388, -0.75098725,  0.41211849,  0.42016704],
       [ 0.95637593,  0.41211849,  0.83665564, -0.8462204 , -0.13235175],
       [-0.75098725, -0.00885131, -0.2794155 , -0.99999021, -0.96139749],
       [ 0.27090579,  0.98935825,  0.14987721,  0.27090579, -0.00885131],
       [-0.54402111, -0.13235175, -0.95892427, -0.99999021, -0.90557836]])

In [167]:
np.log(co2)

array([[3.25809654, 2.56494936, 3.8918203 , 3.58351894, 3.29583687],
       [3.93182563, 3.73766962, 3.68887945, 2.56494936, 4.02535169],
       [2.7080502 , 2.94443898, 3.80666249, 3.68887945, 3.95124372],
       [2.56494936, 2.63905733, 3.21887582, 3.25809654, 4.00733319],
       [3.29583687, 4.06044301, 3.8286414 , 3.33220451, 3.87120101]])

In [168]:
np.cos(co2)

array([[ 0.64691932,  0.90744678,  0.30059254, -0.12796369, -0.29213881],
       [ 0.7421542 , -0.39998531, -0.66693806,  0.90744678,  0.85322011],
       [-0.75968791,  0.98870462,  0.52532199, -0.66693806, -0.16299078],
       [ 0.90744678,  0.13673722,  0.99120281,  0.64691932,  0.02212676],
       [-0.29213881,  0.11918014, -0.43217794, -0.96260587, -0.64014434]])

In [169]:
np.exp(co1)

array([[7.20048993e+10, 3.93133430e+12, 6.56599691e+07, 8.10308393e+03,
        4.42413392e+05],
       [5.32048241e+11, 8.10308393e+03, 1.31881573e+09, 9.74480345e+09,
        7.20048993e+10],
       [6.56599691e+07, 3.58491285e+09, 4.03428793e+02, 5.98741417e+04,
        2.41549528e+07],
       [1.44625706e+12, 2.98095799e+03, 1.78482301e+08, 1.44625706e+12,
        3.58491285e+09],
       [2.20264658e+04, 7.20048993e+10, 1.48413159e+02, 5.98741417e+04,
        2.64891221e+10]])

In [170]:
co2 * 4

array([[104,  52, 196, 144, 108],
       [204, 168, 160,  52, 224],
       [ 60,  76, 180, 160, 208],
       [ 52,  56, 100, 104, 220],
       [108, 232, 184, 112, 192]])

In [171]:
co1 / 5

array([[5. , 5.8, 3.6, 1.8, 2.6],
       [5.4, 1.8, 4.2, 4.6, 5. ],
       [3.6, 4.4, 1.2, 2.2, 3.4],
       [5.6, 1.6, 3.8, 5.6, 4.4],
       [2. , 5. , 1. , 2.2, 4.8]])

In [172]:
co2 ** 3

array([[ 17576,   2197, 117649,  46656,  19683],
       [132651,  74088,  64000,   2197, 175616],
       [  3375,   6859,  91125,  64000, 140608],
       [  2197,   2744,  15625,  17576, 166375],
       [ 19683, 195112,  97336,  21952, 110592]], dtype=int32)

In [173]:
np.dot(co1, co2) #كل سطر يضرب بالعمود المقابل 
#+row1 * +col1 ...etc  ros == cols

array([[2867, 2765, 4018, 2595, 4354],
       [2450, 2900, 4353, 3227, 4790],
       [2282, 2412, 3089, 1936, 3451],
       [2379, 2729, 4259, 3216, 4788],
       [2401, 2821, 3094, 1843, 3687]])

In [174]:
np.sum(co1)

453

In [179]:
co1.sum()

453

In [177]:
co2.sum(axis=1)

array([151, 202, 171, 133, 207])

In [178]:
co1.sum(axis=0)

array([108,  93,  69,  82, 101])

In [180]:
co1.var()

56.58559999999999

In [181]:
co2.std()

14.9454474673728

In [182]:
co1.mean()

18.12

In [184]:
np.corrcoef(co2)

array([[ 1.        , -0.32480045,  0.59922353,  0.16501544, -0.33020228],
       [-0.32480045,  1.        , -0.10424773,  0.26154169,  0.38102032],
       [ 0.59922353, -0.10424773,  1.        ,  0.84514481,  0.12897629],
       [ 0.16501544,  0.26154169,  0.84514481,  1.        ,  0.19088077],
       [-0.33020228,  0.38102032,  0.12897629,  0.19088077,  1.        ]])

In [185]:
np.sort(co1, axis=1)

array([[ 9, 13, 18, 25, 29],
       [ 9, 21, 23, 25, 27],
       [ 6, 11, 17, 18, 22],
       [ 8, 19, 22, 28, 28],
       [ 5, 10, 11, 24, 25]])

In [186]:
np.sort(co2, axis=0)

array([[13, 13, 25, 13, 27],
       [15, 14, 40, 26, 48],
       [26, 19, 45, 28, 52],
       [27, 42, 46, 36, 55],
       [51, 58, 49, 40, 56]])

In [187]:
np.linalg.inv(co1 #معكوس المصفوفة

array([[-0.0345629 ,  0.07138458,  0.16550557, -0.06975434, -0.108929  ],
       [ 0.03864936, -0.07704695, -0.03848815,  0.04996323,  0.04078498],
       [ 0.06781436,  0.01684943, -0.15723482,  0.00578916,  0.05178366],
       [ 0.01394217, -0.1527408 , -0.07949774,  0.16607616,  0.05562741],
       [-0.0463767 ,  0.11700956,  0.04032489, -0.10030504,  0.00828524]])

In [205]:
file_path = "C:\\Users\\asus_r\\AnacondaProjects\\Python Science Libraries\\data.txt"
data_type = np.dtype([('Gender', '|S1'), ('Old', 'i2')])
data = np.loadtxt(file_path, data_type, skiprows=6, usecols=(0,1))
print(data)

[(b'F', 23) (b'M', 33) (b'M', 43) (b'F', 19) (b'F', 40) (b'M', 52)
 (b'F', 22) (b'F', 19) (b'F', 28) (b'M', 25) (b'F', 31) (b'M', 53)
 (b'M', 42) (b'F', 21)]
