<p style="height:100px;line-height:100px;font-size:46px;background-color:lime;color:white;padding-left:12px;">
    SciKit-Learn
</p>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as mpp
import sklearn.datasets as dts
from sklearn.impute import SimpleImputer
import sklearn.feature_selection as fsl
import sklearn.preprocessing as ppr
import sklearn.model_selection as msl
import sklearn.linear_model as lmd
import sklearn.ensemble as ens
import sklearn.metrics as mtr

- **1) Load Data: import sklearn.datasets as dts OR Manuel**
- **2) Cleaning: from sklearn.impute import SimpleImputer OR Manuel**
- **3) Features Selection: import sklearn.feature_selection as fsl OR Manuel**
- **4) Scalling: import sklearn.preprocessing as ppr OR Manuel**
- **5) Spliting: import sklearn.model_selection as msl OR Manuel**

- **X = input : X_train, X_test**
- **y = output : y_pred, y_true**

## Load Data

In [ ]:
IrisData = dts.load_iris()

In [ ]:
IrisData.data[:10]

In [ ]:
IrisData.target[:10]

In [ ]:
IrisData.feature_names

In [ ]:
IrisData.target_names

In [ ]:
df = pd.DataFrame(IrisData.data, columns=IrisData.feature_names)

In [ ]:
DigitsData = dts.load_digits()

In [ ]:
X = [6, 7, 7, 6, 7, 7, 6] #true
Y = [6, 6, 7, 6, 6, 6, 7] #prediction

## Some Meterics

In [ ]:
mtr.mean_absolute_error(X, Y, multioutput='uniform_average')

In [ ]:
mtr.mean_squared_error(X, Y, multioutput='uniform_average')

In [ ]:
mtr.median_absolute_error(X, Y)

In [ ]:
val = mtr.confusion_matrix(X, Y)
val
#[[TP, FP],
# [FN, TN]]

In [ ]:
i = 0
j = 0
vals = []
while i < val.shape[0] and j < val.shape[1]:
    vals.append(val[i,j])
    i += 1
    j += 1
print(vals)

In [ ]:
sb.heatmap(val, center=True)
mpp.show()

In [ ]:
a = mtr.accuracy_score(X, Y) # --------------->  normalize=[True, Flase] default is True
b = mtr.accuracy_score(X, Y, normalize=False)
a, b
#False show onlt True values
#True show True values / Total values

In [ ]:
mtr.recall_score(X, Y, average='micro')   #average = [binary, macro, weighted, samples]
#recall score (Sensitivity) = TP / float(TP + FN)

In [ ]:
mtr.precision_score(X, Y, average='micro')   #average = [binary, macro, weighted, samples]
# precision score (Specificity) = TP / float(TP + FP)

In [ ]:
mtr.f1_score(X, Y, average='micro') #average = [binary, macro, weighted, samples]
#f1 score = 2 * (precision * recall) / (precision + recall)

In [ ]:
mtr.precision_recall_fscore_support(X, Y, average='micro')
#precision_recall_fscore_support(y_true, y_pred, beta=1.0, labels=None, pos_label=1, average=None, sample_weight=None,  
#                                warn_for = ('precision’,’recall’, ’f-score’))
#Return /precision_score-recall_score-f1score-support/


In [ ]:
Y1 = [0, 1, 1, 0, 0, 1]
X1 = [3 , 4, 3, 2, 1, 5]
mtr.precision_recall_curve(Y1, X1)
#precision_recall_curve(y_true, probas_pred, pos_label=None, sample_weight=None)
#Return /precision-recall-thresholds/ just for binary[0,1]

In [ ]:
report = mtr.classification_report(X, Y)
#classification_report(y_true, y_pred, labels=None, target_names=None,sample_weight=None, digits=2, output_dict=False)
print(report)

In [ ]:
#fpr = 1-specificity  (specificity = precision)
#tpr = sensivity   (sensivity = recall)

In [ ]:
fpr_value, tpr_value, thresholds_value = mtr.roc_curve(Y, X, pos_label=2)
fpr_value, tpr_value, thresholds_value
#Return /fpr-tpr-thresholds/

In [ ]:
mtr.auc(fpr_value, tpr_value)

In [ ]:
mtr.roc_auc_score(X, Y)

In [ ]:
mtr.zero_one_loss(X, Y), mtr.zero_one_loss(X, Y, normalize=False)   #normalize=[True, False]
#how much algorithm is wrong True = decimal, False=integer

## Features Selection

In [ ]:
df_houses = pd.read_csv('C:/Users/asus_r/Desktop/Data Center/Data/SKLearn/houses.csv')
df_houses_ = df_houses.drop('long', axis=1)
df_houses_.head(5)

In [ ]:
df_houses.apply(lambda x : sum(x.isnull()), axis=0)

In [ ]:
df_houses_target = df_houses['price']

In [ ]:
df_target_ = np.random.randint(10, 60, 999)

In [ ]:
Sel = fsl.SelectPercentile(score_func=fsl.chi2, percentile=50)
Sel.fit_transform(df_houses_.values, df_target_)

In [ ]:
Sel2 = fsl.GenericUnivariateSelect(score_func=fsl.chi2, mode='k_best', param=5) #mod = ['percentile', 'k_best', 'fpr', 'fdr', 'fwe']
Sel2.fit_transform(df_houses_.values, df_target_)

In [ ]:
Sel3 = fsl.SelectKBest(score_func=fsl.chi2, k=4)
Sel3.fit_transform(df_houses_.values, df_target_)

In [ ]:
model = lmd.LinearRegression()
model2 = ens.RandomForestRegressor()
Sel4 = fsl.SelectFromModel(estimator=model, max_features=None)
Sel4.fit_transform(df_houses_.values, df_target_)

## Scalling

In [ ]:
Data = df_houses
Scaler = ppr.StandardScaler().fit_transform(Data)   #Standardization = (Value - mean) / std'Segma'
Scaler.shape

In [ ]:
Scaler_2 = ppr.MinMaxScaler(feature_range=(0, 1)).fit_transform(Data)     #Normalization = (Value - mean) / range
Scaler.shape

In [ ]:
Scaler_3 = ppr.Normalizer(norm='l1').fit_transform(Data)
#norm=['l1', 'l2', 'max']
#l1 --> value / sum(values in row) --> [2,3,4] --> 2 / (2+3+4)
#l2 --> value / sqrt(sum(valaues**2 in row)) --> [2,3,4] --> 2 / sqrt(square(2) + square(3) + square(4))
#max --> value / max(row) --> [2,3,4] --> 2 / max(row)=4
Scaler_3.shape

In [ ]:
Scaler_4 = ppr.MaxAbsScaler().fit_transform(Data)
#value / max(column) --> [2,1,4,6,3,9] --> 2 / max(col)=9
Scaler_4.shape

In [ ]:
Scaler_5 = ppr.FunctionTransformer(func=lambda x:x, validate=True).fit_transform(Data)
#you can use your func or lambda
Scaler_5

In [ ]:
Scaler_6 = ppr.Binarizer(threshold=200).fit_transform(Data)
#if value > threshold --> value = 1
#elif value < treshold --> value = 0
Scaler_6

In [ ]:
dt = [[1, 3, 4],
      [3, 5, 1],
      [6, 2, 3],
      [9, 3, 5]]
Scaler_7 = ppr.PolynomialFeatures(degree=2, include_bias=True, interaction_only=False).fit_transform(dt)
Scaler_7
#[a, b, c] --> [1, a, b, c, a*a, a*b, a*c, b*c, c*c]

In [ ]:
Scaler_71 = ppr.PolynomialFeatures(degree=2, include_bias=True, interaction_only=True).fit_transform(dt)
Scaler_71
#[a, b, c] --> [1, a, b, c, a*b, a*c, b*c] --. without squares

## Spliting

In [81]:
X, y = np.random.randint(100, 900, 50).reshape(10, 5), np.random.randint(0, 20, 10)
X_test, X_train, y_test, y_train = msl.train_test_split(X, y, test_size=0.60, random_state=42, shuffle=True)

In [108]:
kf = msl.KFold(n_splits=2, random_state=42, shuffle=True)

In [109]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)

TRAIN: [2 3 4 6 9] TEST: [0 1 5 7 8]
X_train 
 [[667 575 457 812 350]
 [364 376 860 353 363]
 [865 745 181 268 802]
 [178 604 653 542 758]
 [296 700 699 437 389]]
X_test 
 [[158 306 254 360 447]
 [771 502 413 308 896]
 [695 667 248 117 296]
 [472 133 375 580 387]
 [764 538 390 354 590]]
y_train 
 [17  1 17  9  2]
y_test 
 [ 3 10  1 17  0]
TRAIN: [0 1 5 7 8] TEST: [2 3 4 6 9]
X_train 
 [[158 306 254 360 447]
 [771 502 413 308 896]
 [695 667 248 117 296]
 [472 133 375 580 387]
 [764 538 390 354 590]]
X_test 
 [[667 575 457 812 350]
 [364 376 860 353 363]
 [865 745 181 268 802]
 [178 604 653 542 758]
 [296 700 699 437 389]]
y_train 
 [ 3 10  1 17  0]
y_test 
 [17  1 17  9  2]


In [110]:
Rkf = msl.RepeatedKFold(n_splits=3, n_repeats=4, random_state=42)
Skf = msl.StratifiedKFold(n_splits=4)
RSkf = msl.RepeatedStratifiedKFold(n_splits=3, n_repeats=3)

In [111]:
L1O = msl.LeaveOneOut()
LPO = msl.LeavePOut(3)

In [112]:
Shf = msl.ShuffleSplit(n_splits=6, test_size=0.3, random_state=42)
SSh = msl.StratifiedShuffleSplit(n_splits=8, test_size=0.2, random_state=42)

In [113]:
Tsr = msl.TimeSeriesSplit(n_splits=5, )

<p style="height:240px;line-height:100px;font-size:64px;background-color:cyan;color:white;padding:20px auto;text-align:center;border:2px outset gold;border-radius:8px;">
    Created by:<br/> <code>Tarek Ghajary</code>
</p>